version: '2'
services:
  openvpn:
    build:
      context: .
    cap_add:
     - NET_ADMIN
    container_name: openvpn
    ports:
     - "1194:1194/udp"
    restart: always
    volumes:
     - ./data/conf:/etc/openvpn
